### ISSUE TITLE
r-bridge crashes on chaining R script's in arcpy

### ISSUE THREAD

**Issue by goriliukasbuxton** [R-ArcGIS/r-bridge#10]
Traceback (most recent call last):
  File "<string>", line 73, in execInThread
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 196, in __call__
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 71, in syncreq
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 431, in sync_request
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 379, in serve
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 337, in _recv
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py", line 50, in recv
  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 166, in read
EOFError: [Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by scw** [comment]
Hello @goriliukasbuxton,

Is this error reproducible from a plain Python prompt? Can you provide a sample script? It looks like this may be an issue interacting with a database connection, you can see if catching the exception from this and delaying the DB connection prior to retrying eliminates the issue.

Thanks,
Shaun

**Comment by goriliukasbuxton** [comment]
Hello Shaun,
I have created R scripts, which reads File Geodatabase tables as inputs. adding time.sleep() function before and after R/arcpy code execution helps, but not always.
Will try to replicate it with ESRI's sample code

**Comment by scdub** [comment]
@goriliukasbuxton, I wasn't able to reproduce this on my own, but if you're still having problems with this and can work with me on a way to reproduce it, I'm happy to help -- closing for now.
